spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: development
server:
  port: 8080
telegram:
  bot:
    username: Ramil192Bot
    token: 8012267063:AAF6h4ylXHTVQ1EXVC3Jdj-h3srjcaeo7EA